use_frameworks!

target 'UtilExtension_Example' do
  platform :ios, '11.0'
  pod 'UtilExtension', :path => '../'
end

target 'UtilExtension_Example_macOS' do
  platform :osx, '11.0'
  pod 'UtilExtension', :path => '../'
end
